### ISSUE TITLE
-cue2ccd does not recognize lsd/sbi patch and does not copy the .bin file to the folder \CCD

### ISSUE THREAD

**Issue by apocalypse1233** [Kippykip/SBITools#2]
Possibly because the code to recognize the file is:

"ElseIf(FileType(BaseName + ".lsd"))"
"LSDToSub(BaseName:String + ".lsd", Subchannel)"

instead of:

"ElseIf(FileType(CUE.BinPath + BaseName + ".lsd"))"
"LSDToSub(CUE.BinPath + BaseName:String + ".lsd", Subchannel)"

The same for .sbi and the fuctions to copy bin to ccd folder and rename to img.

**Comment by RoberMC** [comment]
I can confirm this

**Comment by Kippykip** [comment]
The bug turned out to be a file pathing bug in functions.bmx.
Where if the image/cue path resided locally with SBITools, all paths would try to read filenames such as:
"CoolGame.imgCoolGame.img"
"CoolGame.sbiCoolGame.sbi"

The CUE.BinPath was contains the path to the image, such as "C:\ISOS" and would append "BaseName" on it.
Example:
"C:\ISOS\CoolGame.img"

I for some reason made it, if it found the path locally to SBITools it would set CUE.BinPath to the same thing as the BaseName.
Hence the glitched paths like "CoolGame.imgCoolGame.img" above.

I've fixed it in the new v1.3.1 release and it shouldn't be a problem anymore (hopefully).
I also made it echo to the console where it's trying to load .SBI/.LSD paths from, since it has to be the same base filename as the .CUE and be in the same folder.
